### ISSUE TITLE
 RSBU-CS and  RSBU-CS

### ISSUE THREAD

**Issue by guoyanb** [zhao62/Deep-Residual-Shrinkage-Networks#1]
Hello, the residual shrinkage network is interesting. When I read your codes, I meet some confusion. Is the residual shrinakge block  for  RSBU-CW?  Thanks for your reply.

**Comment by zhao62** [comment]
Yes. It is for RSBU-CW. Thanks for your interest in the paper.

**Comment by guoyanb** [comment]
> Yes. It is for RSBU-CW. Thanks for your interest in the paper.

Ok, thanks
