### ISSUE TITLE
一维信号处理

### ISSUE THREAD

**Issue by ALiangWaiting** [zhao62/Deep-Residual-Shrinkage-Networks#15]
大佬你好 我的研究方向也是有关一维信号处理的， 我想结合代码和论文好好学习一下你的方法，可以分享一下你的一维信号输入的代码嘛 我的邮箱是（1400068101@qq.com） 。 十分感谢你的帮助

**Comment by zhao62** [comment]
您好，非常感谢对这篇论文的兴趣，我把代码传到了Github
https://github.com/zhao62/Deep-Residual-Shrinkage-Networks/blob/master/DRSN_1D_TFLearn.rar

**Comment by ALiangWaiting** [comment]
十分感谢，您的回信，祝您事事顺利！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhao62/Deep-Residual-Shrinkage-Networks"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月17日(星期五) 下午2:50
***@***.***&gt;;
抄送:&nbsp;"ˇ↗丢 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhao62/Deep-Residual-Shrinkage-Networks] 一维信号处理 (Issue #15)





 
您好，非常感谢对这篇论文的兴趣，我把代码传到了Github
 https://github.com/zhao62/Deep-Residual-Shrinkage-Networks/blob/master/DRSN_1D_TFLearn.rar
