### ISSUE TITLE
关于添加噪声

### ISSUE THREAD

**Issue by GA17AI** [zhao62/Deep-Residual-Shrinkage-Networks#16]
请问是给所有的原始振动信号添加不同SNR的噪声，然后划分训练集和测试集，还是先划分训练集和测试集，只对测试集的原始振动信号添加噪声？

**Comment by zhao62** [comment]
我的那篇论文在训练集、测试集，都添加了噪声。
当时设想的场景是：不管是采集数据作为训练集的时候，还是采集测试数据的时候，这些数据都可能是在强噪环境下采集得到的。
或者说，在有些场景下，我们手里面，可能原本就没有干净的、不含噪声的训练集。我们被迫只能在含噪数据上训练机器学习模型。
