### ISSUE TITLE
关于pad_backend函数中padding的疑问

### ISSUE THREAD

**Issue by xcliang2** [zhao62/Deep-Residual-Shrinkage-Networks#2]
你好，很高兴读到你的文章。

    不过我目前有一个疑问，就是在pad_backend中进行padding时，你首先对输入进行扩维，(n, c, h, w)->(n, c, h, w, 1)，然后通过channels_last方式使用spatial_3d_padding针对第2、3、4维进行填充，最后通过squeeze返回(n, c, h, w)，貌似第5维始终没有用到，不知道你扩维使用5D的目的是干什么？还是我理解的有问题？希望得到解答，谢谢。

**Comment by zhao62** [comment]
你好，第5维确实始终没用到。
我写pad_backend函数，是为了对通道数channels进行padding，来匹配恒等路径和残差路径的通道数量。
但是我对Keras不熟，Keras好像没有现成的函数，来实现这个功能。
我只找到了对空间padding的函数，有spatial_2d_padding和spatial_3d_padding。
所以我先扩充一维，然后借助spatial_3d_padding对通道数进行padding，再把多余的一维删掉。
如果有现成的函数，能对通道数进行padding，我就不这么折腾了。

**Comment by xcliang2** [comment]
好的，了解了，谢谢回复。
