### ISSUE TITLE
关于Downsampling和Zero_padding的疑问

### ISSUE THREAD

**Issue by Atsea0107** [zhao62/Deep-Residual-Shrinkage-Networks#3]
作者您好！
在Keras的代码中您提到(it is important to use the pooL-size of (1, 1)) 和 (it is important to use zero padding rather than 1by1 convolution)，我想请教以下这样使用的理由是？因为这和ResNet的处理方式貌似有些不同。如果我理解没错的话，ResNet是通过卷积的方式来改变通道数以及降采样的。那么您所使用这两种方式的理由是？

期待收到您的回复！

**Comment by zhao62** [comment]
您好，我们的这种做法，是参照了何恺明在2016年的一篇文章：https://arxiv.org/abs/1603.05027
这篇文章认为，如果用卷积的方式来匹配特征通道数，会阻碍梯度传递。原句如下：

> Multiplicative manipulations (scaling, gating, 1*1 convolutions, and dropout) on the shortcuts can hamper information propagation and lead to optimization problems.

**Comment by Atsea0107** [comment]
> 您好，我们的这种做法，是参照了何恺明在2016年的一篇文章：https://arxiv.org/abs/1603.05027
> 这篇文章认为，如果用卷积的方式来匹配特征通道数，会阻碍梯度传递。原句如下：
> 
> > Multiplicative manipulations (scaling, gating, 1*1 convolutions, and dropout) on the shortcuts can hamper information propagation and lead to optimization problems.

这篇文章中表示的恒等映射应该指的是每个block的内部？但每一层之间的维度变换文章中好像没有指出？

**Comment by zhao62** [comment]
每个block内部都有一个恒等映射，这个没有疑义。你说的“每一层之间的维度变换”是什么意思呢？这个说法有不同的理解，我不知道您具体指什么。

**Comment by Atsea0107** [comment]
> 每个block内部都有一个恒等映射，这个没有疑义。你说的“每一层之间的维度变换”是什么意思呢？这个说法有不同的理解，我不知道您具体指什么。

我指的是He在ResNet最开始的那篇文章 https://arxiv.org/abs/1512.03385  Table 1. 中例如 conv2 x，conv3 x 之间的维度变换。我仔细想了想，他这个维度的变换也是在恒等映射里处理的，应该就是您前面说的那个会阻碍梯度传递的问题。不知道是不是这样理解

**Comment by Atsea0107** [comment]
也就是说用例如1x1池化以及padding这样的操作，目的在于尽可能地保留原始信息，不对其做其他的操作。可以这样理解吗？

**Comment by zhao62** [comment]
是的。如果残差路径的输出维度增加了，恒等映射的输出维度也应该相应地增加。这样它们才能够加起来。那么恒等路径怎么实现路径的增加呢？一种方式是1*1卷积，还有一种是直接补零。其实在“Deep Residual Learning for Image Recognition”这篇文章中，何恺明讨论了三种方式，在第6页，左上角：

> In Table 3 we compare three options: (A) zero-padding shortcuts are used for increasing dimensions, and all shortcuts are parameterfree (the same as Table 2 and Fig. 4 right); (B) projection shortcuts are used for increasing dimensions, and other
shortcuts are identity; and (C) all shortcuts are projections.

在这篇文章里，(C)的结果最好。但是，后来在“Identity Mappings in Deep Residual Networks”这篇文章里，何恺明又改变了想法，认为恒等映射内部保持绝对恒等，是很重要的。在恒等路径中，添加1*1卷积，会破坏“恒等”，是不利于梯度反向传播的；因为如果采用1*1卷积，那么恒等路径在反向传播时的梯度就不是1了。

如果直接采用补零的方式，让残差路径和恒等路径的特征通道数保持一致，在反向传播的时候，恒等路径的梯度依然为1。它的梯度为1，对于深层残差网络的训练，是有利的。

**Comment by zhao62** [comment]
目的是为了让恒等路径在反向传播时的梯度恒为1。

**Comment by Atsea0107** [comment]
> 目的是为了让恒等路径在反向传播时的梯度恒为1。

好的，我明白了。谢谢您，非常感谢！

**Comment by zhao62** [comment]
不客气。我删掉了这两个“it is important”；因为这个细节可能对实验结果影响不大，可能算不上important。感谢您的关注。
