### ISSUE TITLE
大佬，请问训练数据能够提供一下吗？

### ISSUE THREAD

**Issue by fengsong77** [zhao62/Deep-Residual-Shrinkage-Networks#4]
谢谢！

**Comment by zhao62** [comment]
不好意思呀，不能。我做不了主。

**Comment by fengsong77** [comment]
@zhao62  请问是否有类似的公用数据集推荐一下？

**Comment by zhao62** [comment]
你找找PHM 2009 challenge dataset呢，是差不多的。http://www.phmsociety.org/references/datasets
