### ISSUE TITLE
pytorch版本

### ISSUE THREAD

**Issue by chenxiangzZ** [zhao62/Deep-Residual-Shrinkage-Networks#5]
你好，请问有没有与ResNet50结合的pytorch版本实现呢？

**Comment by zhao62** [comment]
不好意思哈，没有

**Comment by chenxiangzZ** [comment]
那么我按照文中的写法，把我网络中的SENet替换成收缩网络，这种思路可以尝试么？

**Comment by zhao62** [comment]
我也没做过，可以试一下。关于代码，我最开始写的是TFLearn的，后来补充了Keras的，但是Keras这个工具箱本身似乎有bug，有一些相关的报道：https://tech.sina.com.cn/csj/2020-07-15/doc-iivhvpwx5493678.shtml。我没用过pytorch，现在工作了，也很少有时间学。

**Comment by zhao62** [comment]
> 你好，请问有没有与ResNet50结合的pytorch版本实现呢？

我看到一个网友写了残差收缩网络的部分pytorch代码，可以参考一下：https://zhuanlan.zhihu.com/p/337346575
