### ISSUE TITLE
关于阈值选择的问题

### ISSUE THREAD

**Issue by zhoujiasheng666** [zhao62/Deep-Residual-Shrinkage-Networks#6]
您好！读了您的文章，有个地方没有弄明白，关于文章中阈值选择的方法您是通过训练出α然后与原输入或其均值的乘积作为阈值，这样的理论依据是什么呢？或者说这种阈值的选择方式在当前block中存在何种目标函数吗？期待您的回复

**Comment by zhao62** [comment]
您好，
1、这样做的出发点在于：对于软阈值函数，如果阈值太大，那么输出就全部为零了；在软阈值函数中，阈值还必须是正数；采用这种阈值设置方式，是为了让阈值为正，而且不要太大，不要超出合理的范围。
2、这种阈值的选择方式在当前block中没有目标函数。
3、另外我自己的一些感想是，在神经网络里，这些特征都没有明确的物理意义，所以也很难说明阈值的物理意义。

**Comment by zhoujiasheng666** [comment]
好的，十分感谢！

**Comment by zhao62** [comment]
不客气哈，祝科研顺利！
